# Generated by Django 3.1.7 on 2021-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210524_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraws',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
