# Generated by Django 3.1.7 on 2021-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_useraws_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraws',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
