# Generated by Django 3.1.7 on 2021-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_useraws_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraws',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
