# Generated by Django 3.1.7 on 2021-05-27 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_useraws_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.useraws')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service', models.CharField(max_length=100)),
                ('report', models.JSONField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.scanreports')),
            ],
        ),
    ]
