# Generated by Django 3.1.7 on 2021-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_scanreports_servicesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesreport',
            name='test_status',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
