# Generated by Django 3.1.7 on 2021-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_servicesreport_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesreport',
            name='priority',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
